#!/usr/bin/env bash

set -eu -o pipefail

aws --profile="${PROFILE}" ecr get-login-password --region "${REGION}" | \
  docker login --username AWS --password-stdin "${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"

